language: php
dist: xenial

php:
  - 8.0

before_install:
  - sudo apt-get update
  - sudo apt-get install sqlite

install:
  - composer install --no-interaction

before_script:
  - cp .env.sample .env
  - cp phpunit.sample.xml phpunit.xml

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit
  - ./vendor/bin/psalm
